### ISSUE TITLE
On rust-1.69 evcxr-0.14.2 fails `check_for_errors` test

### ISSUE THREAD

**Issue by trofi** [evcxr/evcxr#294]
`nixpkgs` upgraded to `rust-1.69` recently and discovered `evcxr-0.14.2` testsuite failure. Full build log: https://hydra.nixos.org/log/6ymz1i3mp0k2fm43ma8752csnpl1iqaj-evcxr-0.14.2.drv

```
test check_for_errors ... FAILED
...
failures:

---- check_for_errors stdout ----
thread 'check_for_errors' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `["warning 1:15-1:20"]`', evcxr/tests/integration_tests.rs:962:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    check_for_errors

test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 73.33s
```

Might be related to reduced debug info in a new release? https://blog.rust-lang.org/2023/04/20/Rust-1.69.0.html#debug-information-is-not-included-in-build-scripts-by-default-anymore

**Comment by davidlattimore** [comment]
Thanks for raising this. It's [fixed at head](https://github.com/evcxr/evcxr/commit/d84393a388f795e2c3f13ba0eb4017720111e346) - just needed a change to the test

**Comment by Ma27** [comment]
This is not about the error, but about the subsequent warning test. For me the test still fails when building with 1.69 and fd2325c2273299e3d64999b285df81e2ffd58020:

```
evcxr> failures:
evcxr> 
evcxr> ---- check_for_errors stdout ----
evcxr> thread 'check_for_errors' panicked at 'assertion failed: `(left == right)`
evcxr>   left: `[]`,
evcxr>  right: `["warning 1:15-1:20"]`', evcxr/tests/integration_tests.rs:1008:9
evcxr> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
evcxr> 
evcxr> 
evcxr> failures:
evcxr>     check_for_errors
evcxr> 
evcxr> test result: FAILED. 38 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 42.23s
```

**Comment by davidlattimore** [comment]
Ah, right, sorry, I should have read the message more carefully. It looked so similar to the one that my other commit fixed.

Looks like there's no warning for an unused variable, where before there was a warning. Odd though, because I can't seem to reproduce the problem. I tried building and testing at the same commit with 1.69. I also checked the CI, which ran on that commit, also with 1.69.0 and it passed.

Perhaps I need to try it on nix in order to reproduce?

What happens if you compile the following code with the same rust compiler?

```rust
#![allow(unused_imports, unused_mut, dead_code)]
fn foo() {let mut s = String::new();}

            struct EvcxrUserCodeError {}
            impl<T: std::fmt::Display> From<T> for EvcxrUserCodeError {
                fn from(error: T) -> Self {
                    eprintln!("{}", error);
                    
                    EvcxrUserCodeError {}
                }
            }
        
fn evcxr_variable_store<T: 'static>(_: T) {}
#[allow(unused_variables)]
async fn evcxr_analysis_wrapper(
) -> Result<(), EvcxrUserCodeError> {
Ok(())
}

```

```sh
rustc --edition=2021 --crate-type cdylib lib.rs
```

For me at least, this gives a warning that the variable `s` is unused.

```
warning: unused variable: `s`
 --> lib.rs:2:19
  |
2 | fn foo() {let mut s = String::new();}
  |                   ^ help: if this is intentional, prefix it with an underscore: `_s`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

```

I'm using rust via rustup.

**Comment by Ma27** [comment]
I'll try to take a closer look this week.
